// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BuildManager.Library.DataBaseModels;

public partial class SetUsableItemSlots
{
    public int SetUsableItemSlotsId { get; set; }

    public short? SetId { get; set; }

    public bool? HasMediumHead { get; set; }

    public bool? HasMediumShoulder { get; set; }

    public bool? HasMediumChest { get; set; }

    public bool? HasMediumBelt { get; set; }

    public bool? HasMediumGloves { get; set; }

    public bool? HasMediumPants { get; set; }

    public bool? HasLightHead { get; set; }

    public bool? HasLightShoulder { get; set; }

    public bool? HasLightChest { get; set; }

    public bool? HasLightBelt { get; set; }

    public bool? HasLightGloves { get; set; }

    public bool? HasLightPants { get; set; }

    public bool? HasHeavyHead { get; set; }

    public bool? HasHeavyShoulder { get; set; }

    public bool? HasHeavyChest { get; set; }

    public bool? HasHeavyBelt { get; set; }

    public bool? HasHeavyGloves { get; set; }

    public bool? HasHeavyPants { get; set; }

    public bool? HasNecklace { get; set; }

    public bool? HasRing { get; set; }

    public bool? HasFlame { get; set; }

    public bool? HasFrost { get; set; }

    public bool? HasLightning { get; set; }

    public bool? HasResto { get; set; }

    public bool? HasDagger { get; set; }

    public bool? HasSword { get; set; }

    public bool? HasMace { get; set; }

    public bool? HasAxe { get; set; }

    public bool? HasGreatsword { get; set; }

    public bool? HasMaul { get; set; }

    public bool? HasBattleaxe { get; set; }

    public bool? HasShield { get; set; }

    public virtual SetList Set { get; set; }
}